
import type { Transformation } from './types';

export const TRANSFORMATIONS: Transformation[] = [
  { title: "Custom Prompt", prompt: "CUSTOM", emoji: "✍️" },
  { title: "Cinematic Light", prompt: "Add a dramatic, cinematic lighting effect.", emoji: "🎬" },
  { title: "Watercolor", prompt: "Turn the image into a watercolor painting.", emoji: "🎨" },
  { title: "Vintage 70s", prompt: "Make it look like a vintage photograph from the 1970s.", emoji: "🎞️" },
  { title: "Wildflowers", prompt: "Add a field of vibrant wildflowers in the foreground.", emoji: "🌸" },
  { title: "Winter Scene", prompt: "Change the season to a snowy winter landscape.", emoji: "❄️" },
  { title: "Cyberpunk", prompt: "Transform the scene into a futuristic cyberpunk city.", emoji: "🤖" },
  { title: "Spooky Vibe", prompt: "Give it a spooky, haunted atmosphere with fog and dim light.", emoji: "👻" },
  { title: "Charcoal Sketch", prompt: "Make the subject look like a hand-drawn charcoal sketch.", emoji: "✏️" },
  { title: "Dragon in Sky", prompt: "Add a majestic dragon flying in the sky.", emoji: "🐉" },
  { title: "Film Noir", prompt: "Convert the image to a black and white film noir style.", emoji: "🕵️" },
  { title: "Mars Surface", prompt: "Place the subject on the surface of Mars.", emoji: "🪐" },
  { title: "Magical Aura", prompt: "Surround the subject with a magical, glowing aura.", emoji: "✨" },
  { title: "Van Gogh Style", prompt: "Reimagine the photo in the style of Van Gogh's 'Starry Night'.", emoji: "🌌" },
  { title: "Water Reflection", prompt: "Add a reflection in a pool of water.", emoji: "💧" },
  { title: "Golden Hour", prompt: "Change the time of day to a beautiful golden hour sunset.", emoji: "🌅" },
  { title: "16-Bit Pixel Art", prompt: "Make it a pixel art scene from a 16-bit video game.", emoji: "👾" },
  { title: "Add a Cat", prompt: "Add a cute, fluffy cat sitting next to the main subject.", emoji: "🐈" },
  { title: "Tokyo Night", prompt: "Turn the background into a bustling Tokyo street at night.", emoji: "🌃" },
  { title: "Psychedelic", prompt: "Make the colors hyper-saturated and psychedelic.", emoji: "🍄" },
  { title: "Low-Poly Style", prompt: "Render the image in a low-poly geometric style.", emoji: "🔷" },
  { title: "Holograms", prompt: "Add futuristic holographic displays around the subject.", emoji: " hologram" },
  { title: "Enchanted Forest", prompt: "Change the setting to an enchanted forest with glowing mushrooms.", emoji: "🌳" },
  { title: "Steampunk", prompt: "Give the subject steampunk-style goggles and gears.", emoji: "⚙️" },
  { title: "Double Exposure", prompt: "Create a double exposure effect with a forest silhouette.", emoji: "🌲" },
  { title: "Classic Anime", prompt: "Make it look like a frame from a classic anime film.", emoji: "🎌" },
  { title: "Rainbow", prompt: "Add a rainbow arching across the sky.", emoji: "🌈" },
  { title: "Floating Lanterns", prompt: "Surround the scene with floating lanterns.", emoji: "🏮" },
  { title: "Roman Mosaic", prompt: "Transform it into an ancient Roman mosaic.", emoji: "🏛️" },
  { title: "Galaxy Sky", prompt: "Make the sky filled with swirling galaxies and nebulae.", emoji: "🌠" },
  { title: "Rainy Day", prompt: "Add a gentle rain effect with glistening droplets.", emoji: "☔" },
  { title: "Ancient Ruins", prompt: "Place a mysterious, ancient ruin in the background.", emoji: "🏺" },
  { title: "Medieval Armor", prompt: "Change the clothing of the person to medieval armor.", emoji: "🛡️" },
  { title: "Old Parchment", prompt: "Make the image look like it's printed on old, weathered parchment.", emoji: "📜" },
  { title: "Hot Air Balloon", prompt: "Add a whimsical hot air balloon floating in the distance.", emoji: "🎈" },
  { title: "Underwater", prompt: "Create an underwater version of the scene.", emoji: "🐠" },
  { title: "Pop Art", prompt: "Give it a pop art style like Andy Warhol.", emoji: "🖼️" },
  { title: "Ghostly", prompt: "Add ghostly apparitions in the background.", emoji: "👻" },
  { title: "Jungle Scene", prompt: "Turn it into a lush, overgrown jungle scene.", emoji: "🌴" },
  { title: "Marble Statue", prompt: "Make the main subject appear as a marble statue.", emoji: "🗿" },
  { title: "Lens Flare", prompt: "Add a dramatic lens flare effect.", emoji: "☀️" },
  { title: "Zen Garden", prompt: "Change the background to a serene Japanese zen garden.", emoji: "🏯" },
  { title: "Autumn Leaves", prompt: "Cover the landscape in a blanket of colorful autumn leaves.", emoji: "🍂" },
  { title: "Ink Drawing", prompt: "Make it look like a detailed ink drawing.", emoji: "✒️" },
  { title: "Robot Companion", prompt: "Add a friendly robot companion to the scene.", emoji: "🤖" },
  { title: "Snow Globe", prompt: "Place the scene inside a crystal snow globe.", emoji: "🔮" },
  { title: "Documentary Photo", prompt: "Give it a grainy, high-contrast B&W documentary photo look.", emoji: "📷" },
  { title: "Butterflies", prompt: "Add butterflies fluttering around the subject.", emoji: "🦋" },
  { title: "Fairytale", prompt: "Transform it into a scene from a fairytale.", emoji: "🏰" },
  { title: "Chessboard Ground", prompt: "Make the ground look like a giant chessboard.", emoji: "♟️" },
  { title: "Magical Particles", prompt: "Surround the subject with shimmering, magical particles.", emoji: "✨" },
];
